using Microsoft.EntityFrameworkCore;
using LoreTest.Data;

namespace LoreTest.Utilities
{
    public static class LocalizationSeeder
    {
        public static async Task SeedAsync(IServiceProvider serviceProvider)
        {
            using var scope = serviceProvider.CreateScope();
            var context = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

            // Ensure English language exists
            var english = await context.SupportedLanguages.FirstOrDefaultAsync(l => l.Code == "en");
            if (english == null)
            {
                english = new SupportedLanguage { Code = "en", Name = "English", IsDefault = true };
                context.SupportedLanguages.Add(english);
                await context.SaveChangesAsync();
            }

            // List of initial translations from SharedResource.en.resx
            var initialTranslations = new Dictionary<string, string>
            {
                { "Home", "Dashboard" },
                { "Users", "Users" },
                { "Projects", "Projects" },
                { "TestRuns", "Test Runs" },
                { "Bugs", "Bugs" },
                { "Logout", "Logout" },
                { "Register", "Register" },
                { "Login", "Login" },
                { "Settings", "Settings" },
                { "PreferredLanguage", "Preferred Language" },
                { "Profile", "Profile" },
                { "Save", "Save" },
                { "WelcomeTitle", "Dashboard" },
                { "WelcomeMessage", "Welcome to your new app." },
                { "ManageUsers", "Manage Application Users" },
                { "About", "About" },
                { "CreateNew", "Create New" },
                { "Loading", "Loading..." },
                { "Email", "Email" },
                { "Name", "Name" },
                { "JobTitle", "Job Title" },
                { "Role", "Role" },
                { "StartDate", "Start Date" },
                { "EndDate", "End Date" },
                { "Edit", "Edit" },
                { "Delete", "Delete" },
                { "CreateUser", "Create User" },
                { "Password", "Password" },
                { "SelectRole", "Select a Role..." },
                { "Editor", "Editor" },
                { "Tester", "Tester" },
                { "Reviewer", "Reviewer" },
                { "BackToList", "Back to List" },
                { "EditUser", "Edit User" },
                { "DeleteUser", "Delete User" },
                { "DeleteConfirmation", "Are you sure you want to delete this user?" },
                { "TestProjects", "Test Projects" },
                { "NoProjectsFound", "No projects found." },
                { "ReferenceNo", "Reference No." },
                { "Title", "Title" },
                { "Description", "Description" },
                { "Actions", "Actions" },
                { "Details", "Details" },
                { "CreateTestProject", "Create Test Project" },
                { "ProjectDetails", "Project Details" },
                { "ProjectTitlePrefix", "Project: " },
                { "TestSuites", "Test Suites" },
                { "CreateNewTestSuite", "Create New Test Suite" },
                { "StartTestRun", "Start Test Run" },
                { "NoTestSuitesFound", "No test suites found for this project." },
                { "ViewTestCases", "View Test Cases" },
                { "EditTestProject", "Edit Test Project" },
                { "DeleteTestProject", "Delete Test Project" },
                { "DeleteConfirmationGeneral", "Are you sure you want to delete this?" },
                { "NoPermissionCreateTestSuite", "You do not have permission to create test suites." },
                { "BackToProject", "Back to Project" },
                { "DeleteTestSuite", "Delete Test Suite" },
                { "NoPermissionDeleteTestSuite", "You do not have permission to delete test suites." },
                { "DeleteTestSuiteConfirmation", "Are you sure you want to delete this test suite?" },
                { "DeleteTestSuiteWarning", "This will also delete all test cases and steps associated with it." },
                { "TestCases", "Test Cases" },
                { "Cancel", "Cancel" },
                { "TestSuiteDetails", "Test Suite Details" },
                { "TestSuiteTitlePrefix", "Test Suite: " },
                { "EditSuite", "Edit Suite" },
                { "DeleteSuite", "Delete Suite" },
                { "AddTestCase", "+ Add Test Case" },
                { "NoTestCasesFound", "No test cases found in this suite." },
                { "Priority", "Priority" },
                { "Status", "Status" },
                { "View", "View" },
                { "CreateTestCase", "Create Test Case" },
                { "NoPermissionCreateTestCase", "You do not have permission to create test cases." },
                { "PreConditions", "Pre-Conditions" },
                { "Dependencies", "Dependencies" },
                { "TestData", "Test Data" },
                { "PostCondition", "Post-Condition" },
                { "SelectStatus", "-- Select Status --" },
                { "Pending", "Pending" },
                { "Pass", "Pass" },
                { "Fail", "Fail" },
                { "SelectPriority", "-- Select Priority --" },
                { "Low", "Low" },
                { "Medium", "Medium" },
                { "High", "High" },
                { "DefectId", "Defect ID (Link)" },
                { "Notes", "Notes" },
                { "DeleteTestCase", "Delete Test Case" },
                { "NoPermissionDeleteTestCase", "You do not have permission to delete test cases." },
                { "TestCase", "Test Case" },
                { "TestCaseDetails", "Test Case Details" },
                { "EditCase", "Edit Case" },
                { "DeleteCase", "Delete Case" },
                { "CaseDetails", "Case Details" },
                { "TestSteps", "Test Steps" },
                { "Overview", "Overview" },
                { "IdRef", "ID / Ref" },
                { "None", "None" },
                { "StepsForThisCase", "Steps for this test case" },
                { "AddStep", "+ Add Step" },
                { "NoStepsAdded", "No steps added yet." },
                { "ClickAddStep", "Click \"+ Add Step\" to create the first step." },
                { "StepDescription", "Step Description" },
                { "ExpectedResult", "Expected Result" },
                { "ActualResult", "Actual Result" },
                { "EditPrefix", "Edit: " },
                { "SaveCase", "Save Case" },
                { "NoStepsYetFormBelow", "No steps yet — use the form below to add the first one." },
                { "AddNewStep", "Add New Step" },
                { "StepPrefix", "Step " },
                { "StepNumberPrefix", "Step #" },
                { "IfDifferent", "(if different)" },
                { "BackToDetails", "Back to Details" },
                { "AddTestStep", "Add Test Step" },
                { "NoPermissionAddTestStep", "You do not have permission to add test steps." },
                { "StepNumber", "Step Number" },
                { "StepNumberHelp", "Auto-assigned as the next sequential number. Adjust if needed." },
                { "SaveStep", "Save Step" },
                { "AddStepPrefix", "Add Step " },
                { "DeleteTestStep", "Delete Test Step" },
                { "NoPermissionDeleteTestStep", "You do not have permission to delete test steps." },
                { "DeleteStepPrefix", "Delete Step " },
                { "DeleteStepConfirmation", "Are you sure you want to permanently delete this step?" },
                { "ActionCannotBeUndone", "This action cannot be undone." },
                { "YesDeleteStep", "Yes, Delete Step" },
                { "EditTestStep", "Edit Test Step" },
                { "NoPermissionEditTestStep", "You do not have permission to edit test steps." },
                { "EditStepPrefix", "Edit Step " },
                { "StartNewRunFromProjects", "Start New Run (from Projects)" },
                { "NoTestRunsRecorded", "No test runs have been recorded yet." },
                { "RunNumberPrefix", "Run #" },
                { "DateStarted", "Date Started" },
                { "StartedBy", "Started By" },
                { "Result", "Result" },
                { "Completed", "Completed" },
                { "Resume", "Resume" },
                { "PassSummary", "{0} Pass" },
                { "FailSummary", "{0} Fail" },
                { "SetupTestRun", "Setup Test Run" },
                { "LoadingProject", "Loading project..." },
                { "SelectTestSuite", "Select Test Suite:" },
                { "SelectASuite", "-- Select a Suite --" },
                { "SelectTestCases", "Select Test Cases" },
                { "SuiteHasNoTestCases", "This suite has no test cases." },
                { "SelectAll", "Select All" },
                { "SelectNone", "Select None" },
                { "StartExecution", "Start Execution" },
                { "TestRunDetails", "Test Run Details" },
                { "LoadingDetails", "Loading details..." },
                { "RunDetailsPrefix", "Run #{0} Details" },
                { "ResumeExecution", "Resume Execution" },
                { "Summary", "Summary" },
                { "Started", "Started" },
                { "Finished", "Finished" },
                { "Duration", "Duration" },
                { "PassRate", "{0}% Pass Rate" },
                { "Other", "Other" },
                { "PassedUpper", "PASSED" },
                { "FailedUpper", "FAILED" },
                { "TotalCasesUpper", "TOTAL CASES" },
                { "ReportBug", "Report Bug" },
                { "NotRun", "Not Run" },
                { "ReportBugFromTestResult", "Report Bug from Test Result" },
                { "DescriptionReproSteps", "Description / Repro Steps" },
                { "Severity", "Severity" },
                { "SaveBugReport", "Save Bug Report" },
                { "ExecuteTestRun", "Execute Test Run" },
                { "LoadingRunPrefix", "Loading Test Run #{0}..." },
                { "ExecutionCompleted", "Execution Completed!" },
                { "RunCompletedOn", "This test run was completed on {0}." },
                { "ViewFinalResults", "View Final Results" },
                { "Execution", "Execution" },
                { "ProgressSummary", "{0}% Complete ({1} / {2} Steps)" },
                { "CaseOfTotal", "Case {0} of {1}" },
                { "Requirements", "Requirements" },
                { "NoDescriptionProvided", "No description provided." },
                { "NoExpectedResultDefined", "No expected result defined." },
                { "ActualExecution", "Actual Execution" },
                { "SetStatus", "Set Status:" },
                { "ActualResultNotes", "Actual Result / Notes:" },
                { "DescribeWhatHappened", "Describe what actually happened..." },
                { "PreviousStep", "Previous Step" },
                { "NextStep", "Next Step" },
                { "CompleteTestRun", "Complete Test Run" },
                { "RunProgressLog", "Run Progress Log" },
                { "ReportBugFromExecution", "Report Bug from Execution" },
                { "SaveBugContinue", "Save Bug & Continue Test" },
                { "BugReports", "Bug Reports" },
                { "ReportNewBug", "Report New Bug" },
                { "NoBugsFound", "No bugs found." },
                { "Reporter", "Reporter" },
                { "Assignee", "Assignee" },
                { "Unknown", "Unknown" },
                { "Unassigned", "Unassigned" },
                { "Critical", "Critical" },
                { "Major", "Major" },
                { "Minor", "Minor" },
                { "Cosmetic", "Cosmetic" },
                { "Open", "Open" },
                { "InProgress", "In Progress" },
                { "Resolved", "Resolved" },
                { "Closed", "Closed" },
                { "Reopened", "Reopened" },
                { "BugDetailsTitle", "Bug Details - {0}" },
                { "BugIdPrefix", "Bug #{0}:" },
                { "EditBug", "Edit Bug" },
                { "DescriptionReproductionSteps", "Description & Reproduction Steps" },
                { "NA", "N/A" },
                { "Resolution", "Resolution" },
                { "Attachments", "Attachments" },
                { "NoAttachmentsFound", "No attachments found." },
                { "Attributes", "Attributes" },
                { "Environment", "Environment" },
                { "NotSpecified", "Not specified" },
                { "Components", "Components" },
                { "Labels", "Labels" },
                { "PeopleAndDates", "People & Dates" },
                { "Reported", "Reported" },
                { "DueDate", "Due Date" },
                { "AffectedVersion", "Affected Version" },
                { "FixVersion", "Fix Version" },
                { "TBD", "TBD" },
                { "TitlePlaceholder", "Short descriptive title" },
                { "DescriptionPlaceholder", "1. Go to... 2. Click on..." },
                { "EnvironmentPlaceholder", "OS, Browser, Device..." },
                { "ComponentsPlaceholder", "UI, API, Database..." },
                { "LabelsPlaceholder", "regression, ui-glitch, etc." },
                { "AttachmentsLabel", "Attachments (Screenshots, Docs)" },
                { "CreateBugReport", "Create Bug Report" },
                { "EditBugTitle", "Edit Bug #{0}" },
                { "ResolutionNotes", "Resolution Notes" },
                { "ResolutionPlaceholder", "How was this fixed?" },
                { "PageNotFound", "Not Found" },
                { "NotFoundMessage", "Sorry, the content you are looking for does not exist." },
                { "ErrorTitle", "Error" },
                { "ErrorMessage", "An error occurred while processing your request." },
                { "RequestID", "Request ID" },
                { "DevelopmentMode", "Development Mode" },
                { "AuthRequired", "Auth Required" },
                { "UnhandledError", "An unhandled error has occurred." },
                { "Reload", "Reload" },
                { "LoginTitle", "Log in" },
                { "UseLocalAccount", "Use a local account to log in." },
                { "RememberMe", "Remember me" },
                { "LoginButton", "Log in" },
                { "OrSeparator", "OR" },
                { "LoginWithPasskey", "Log in with a passkey" },
                { "ForgotPasswordLink", "Forgot your password?" },
                { "RegisterAsNewUser", "Register as a new user" },
                { "ResendEmailConfirmation", "Resend email confirmation" },
                { "AdminSettings", "Admin Settings" },
                { "TranslationServiceSettings", "Translation Service Settings" },
                { "TranslationAPI", "Translation API" },
                { "TranslationApiHelp", "Select the external service provider to use for on-the-fly content translation." },
                { "APIKey", "API Key" },
                { "ApiKeyHelp", "The authentication key provided by your API vendor." },
                { "SaveSettings", "Save Settings" },
                { "SettingsSavedSuccessfully", "Settings saved successfully!" },
                { "Internationalization", "Internationalization" },
                { "ManageLanguagesAndTranslationsHelp", "Configure supported languages and override field headings dynamically." },
                { "ManageLanguages", "Manage Languages" },
                { "ManageFieldTranslations", "Manage Field Translations" },
                { "SupportedLanguages", "Supported Languages" },
                { "AddLanguage", "Add Language" },
                { "AddNewLanguage", "Add New Language" },
                { "Code", "Code" },
                { "Default", "Default" },
                { "SetAsDefault", "Set as Default" },
                { "SelectLanguage", "Select Language" },
                { "ChooseLanguage", "Choose Language" },
                { "FieldKey", "Field Key" },
                { "TranslatedValue", "Translated Value" },
                { "AddTranslation", "Add Translation" },
                { "EditTranslation", "Edit Translation" },
                { "Translations", "Translations" },
                { "Yes", "Yes" },
                { "No", "No" },
                { "ExportCSV", "Export CSV" },
                { "ImportCSV", "Import CSV" },
                { "SelectCSVFile", "Select CSV File" },
                { "Importing", "Importing..." },
                { "ImportSuccessful", "Import successful!" },
                { "ImportError", "An error occurred during import." },
                { "ImportInstructions", "The CSV should have columns: Test Suite Title, Test Suite Description, Test Case Title, Test Case Description, Test Step, Test Step Expected Result." },
                { "MyActiveTasks", "My Active Tasks" },
                { "RunsInProgress", "Runs In Progress" },
                { "LastWeekRuns", "Last Week's Runs" },
                { "CompletedIn7Days", "Completed in last 7 days" },
                { "WeeklyPasses", "Weekly Passes" },
                { "TestCasesPassed", "Test cases passed" },
                { "WeeklyFailures", "Weekly Failures" },
                { "TestCasesFailed", "Test cases failed" },
                { "NoActiveTasks", "You have no active test runs at the moment." },
                { "Suite", "Suite" },
                { "Progress", "Progress" },
                { "QuickLinks", "Quick Links" },
                { "StartNewRun", "Start New Test Run" },
                { "BrowseProjects", "Browse Projects" },
                { "SystemSummary", "System Summary" },
                { "SystemStatsMessage", "In the last 7 days, {0} test cases have been executed across {1} test runs." },
                { "AuditReport", "Audit Report" },
                { "DataAuditReport", "Data Audit Report" },
                { "AllTables", "All Tables" },
                { "AllActions", "All Actions" },
                { "UserIdOrName", "User ID or Name" },
                { "ApplyFilters", "Apply Filters" },
                { "NoAuditLogsFound", "No audit logs found matching your criteria." },
                { "Timestamp", "Timestamp" },
                { "Column", "Column" },
                { "OldValue", "Old Value" },
                { "NewValue", "New Value" },
                { "ShowingLastLogs", "Showing last {0} entries" }
            };

            var keys = initialTranslations.Keys.ToList();
            for (int i = 0; i < keys.Count; i++)
            {
                var key = keys[i];
                var value = initialTranslations[key];
                var fieldId = i + 1;

                // Ensure field exists in LocalizationFields
                var field = await context.LocalizationFields.FirstOrDefaultAsync(f => f.Id == fieldId);
                if (field == null)
                {
                    field = new LocalizationField { Id = fieldId, Key = key };
                    context.LocalizationFields.Add(field);
                }
                else
                {
                    field.Key = key;
                    context.LocalizationFields.Update(field);
                }

                await context.SaveChangesAsync();

                // Ensure English translation exists
                var existing = await context.DynamicTranslations
                    .FirstOrDefaultAsync(t => t.LanguageId == english.Id && t.FieldId == fieldId);

                if (existing == null)
                {
                    context.DynamicTranslations.Add(new DynamicTranslation
                    {
                        LanguageId = english.Id,
                        FieldId = fieldId,
                        TranslatedValue = value
                    });
                }
                else
                {
                    existing.TranslatedValue = value;
                    context.DynamicTranslations.Update(existing);
                }
            }

            await context.SaveChangesAsync();
        }
    }
}
